---
# ####################################################################################
# This is the main playbook, which is used to call all the roles that will allow the
# installation of Oracle JDK, Oracle Weblogic and Oracle SOA
# ####################################################################################

- hosts: soa
  remote_user: "{{ oracle_user }}"
  tasks:

  #  - name: Name
  #    debug:
  #      msg: "{{ soa_binaries['weblogic12214']['name'] }}"

  #  - name: Version
  #    debug:
  #      msg: "{{ soa_binaries['weblogic12214']['version'] }}"

  #  - name: staging
  #    debug:
  #      msg: "{{ soa_binaries['weblogic12214']['staging'] }}"

  #  - name: installer_name
  #    debug:
  #      msg: "{{ soa_binaries['weblogic12214']['installer_name'] }}"

  #  - name: package
  #    debug:
  #      msg: "{{ soa_binaries['weblogic12214']['patches']['p1']['package'] }}"
  
  # - name: Looping dictionaries
  #   debug: 
  #     msg: 
  #       - "{{ item.staging }}"
  #   with_items:
  #    - "{{ soa_installers }}"

   - name: Setting list patches
     set_fact:
       list_patches: "{{ soa_installers | json_query('[?installer== `weblogic12214`][].patches[?patch!= `\"28186730\"`][]')  }}"

   - name: Looping list patches
     debug:
       msg: "{{ item.zipname }}"
     loop: "{{ list_patches }}"
