---
# I want to set a configuration file based on YAML with the most important 
# information at a global level. This configuration can be used by different roles
# and or playbooks

# Directory where installers are copy from
source_directory: /u01/software
# Directory where installers are copy to
staging_directory: /u01/staging
# The user that will run Weblogic
oracle_user: oracle
# The oracle's group
oracle_group: oinstall
# The home where Oracle products will be installed
oracle_home: "/u01/{{ oracle_user }}/product"
# Directory where patches are copy to
patch_directory: "{{ staging_directory }}/patches"

# This list of dictionaries is used to configure all the installers needed to create an
# Oracle SOA domain. 
soa_installers:
  - installer: jdk8u251
    name: Oracle JDK
    version: 8u251
    java_home: "/u01/{{ oracle_user }}/java/jdk"
    staging: stgjdk8u251         # To  create a directory in "{{ staging_directory }}"
    filename: jdk-8u251-linux-x64.tar.gz
    zipname: jdk-8u251-linux-x64.tar.gz
  - installer: weblogic12214
    name: Oracle Weblogic 
    version: 12.2.1.4
    staging: stgweblogic12214    # To  create a directory in "{{ staging_directory }}"
    filename: fmw_12.2.1.4.0_wls.jar
    zipname: WEBLOGIC_12.2.1.4_V983364-01.zip
    patches: 
      - patch: "30970477"
        zipname: p30970477_122140_Generic.zip
      - patch: "28186730"           # To patch opatch
        zipname: p28186730_139422_Generic.zip
  - installer: soa12214
    name: Oracle SOA
    version: 12.2.1.4
    staging: stgsoa12214         # To  create a directory in "{{ staging_directory }}"
    filename: fmw_12.2.1.4.0_soa.jar
    zipname: SOA_12.2.1.4_V983383-01.zip
    patches:
      - patch: "30995852"
        zipname: p30995852_122140_Generic.zip        
