---
# I want to set a configuration file based on YAML with the most important 
# information at a global level. This configuration can be used by different roles
# and or playbooks

# Directory where installers are copy from
source_directory: /u01/software
# Directory where installers are copy to
staging_directory: /u01/staging
# The user that will run Weblogic
oracle_user: oracle
# The home where Oracle products will be installed
oracle_home: "/u01/{{ oracle_user }}/product"

# This dictionary is used to configure all the installers needed to create an
# Oracle SOA domain. 
soa_binaries:
  jdk8u251:
    name: Oracle JDK
    version: 8u251
    java_home: "/u01/{{ oracle_user }}/java/jdk"
    staging: stgjdk8u251         # To  create a directory in "{{ staging_directory }}"
    installer_name: jdk-8u251-linux-x64.tar.gz
  weblogic12214:
    name: Oracle Weblogic 
    version: 12.2.1.4
    staging: stgweblogic12214    # To  create a directory in "{{ staging_directory }}"
    installer_name: fmw_12.2.1.4.0_wls.jar
    package: WEBLOGIC_12.2.1.4_V983364-01.zip
    patches:
    "30970477":
      staging: patches/stgweblogic12214
      package: p30970477_122140_Generic.zip
  soa12214:
    name: Oracle SOA
    version: 12.2.1.4
    staging: stgsoa12214         # To  create a directory in "{{ staging_directory }}"
    installer_name: fmw_12.2.1.4.0_soa.jar
    package: SOA_12.2.1.4_V983383-01.zip
    patches:
      "30995852":
        staging: patches/stgsoa12214
        package: p30995852_122140_Generic.zip    
  "28186730":
    name: Opatch patch    
    version: 13.9.4.2.2
    staging: patches/opatch139422
    package: p28186730_139422_Generic.zip