---
  - name: Getting configuration to run RCU
    set_fact:
      connection_string: "{{ soa_domain | json_query('[][].rcu[].connectionstring') | join(',') }}"
      db_user: "{{ soa_domain | json_query('[][].rcu[].dbuser') | join(',') }}"
      db_role: "{{ soa_domain | json_query('[][].rcu[].dbrole') | join(',') }}"
      schema_prefix: "{{ soa_domain | json_query('[][].rcu[].schemaprefix') | join(',') }}"
      same_password: "{{ soa_domain | json_query('[][].rcu[].samepasswordallusers[]') | join(' ') }}"
      list_components: "{{ soa_domain | json_query('[][].rcu[].components[]') | join(' ') }}"
      db_password: "{{ soa_domain | json_query('[][].rcu[].dbpassword[]') | join(' ') }}"
      schema_password: "{{ soa_domain | json_query('[][].rcu[].schemapassword[]') | join(' ') }}"
    no_log: yes

  - name: Executing RCU
    expect:
      command:
        "{{ oracle_common }}/bin/rcu -silent -createRepository -connectString {{ connection_string }} \
          -dbUser {{ db_user  }} -dbRole {{ db_role }} -schemaPrefix {{ schema_prefix }} \
          -useSamePasswordForAllSchemaUsers {{ same_password|lower }} {{ list_components }}"
      responses:
        'Enter the database password': "{{ db_password }}"
        'Enter the schema password': "{{ schema_password }}"
      timeout: 1200 # Expect timeout by default is 30s. Here, I am using 20 minutes as RCU is slow
    no_log: yes
    register: rcu_output
    # The error RCU-6016 means the schemas with given prefix are in the database
    failed_when: "'ERROR - RCU' in rcu_output.stdout and 'CAUSE - RCU-6016' not in rcu_output.stdout"

  - name: Show warning if schemas have been created before
    debug:
      msg: "Schemas with prefix {{ schema_prefix }} have been created before.Thus, RCU creation has been skipped"
    when: "'CAUSE - RCU-6016' in rcu_output.stdout"