  - name: Getting configuration to install Weblogic and SOA
    set_fact:
      # Even thoug each expression returns just one value. I used "join" to convert the variable
      # into a string
      install_java_home: "{{ soa_installers | json_query('[?installer == `jdk8u251`].java_home')|join(',') }}"
      install_soa_staging: "{{ soa_installers | json_query('[?installer == `soa12214`].staging')|join(',') }}"
      install_soa_zip: "{{ soa_installers | json_query('[?installer == `soa12214`].zipname')|join(',') }}"
      install_soa_file: "{{ soa_installers | json_query('[?installer == `soa12214`].filename')|join(',') }}"
      install_soa_rsp_file: "{{ soa_installers | json_query('[?installer == `soa12214`].responsefile')|join(',') }}"
      install_soa_memory: "{{ soa_installers | json_query('[?installer == `soa12214`].memorysettings')|join(',') }}"

  - name: Unzip SOA installer
    unarchive:
      remote_src: yes
      src: "{{ staging_directory }}/{{ install_soa_staging }}/{{ install_soa_zip }}"
      dest: "{{ staging_directory }}/{{ install_soa_staging }}"
      creates: "{{ staging_directory }}/{{ install_soa_staging }}/{{ install_soa_file }}"

  - name: "Using a template to create the Weblogic response file"
    template:
      src: weblogic.rsp.j2
      dest: "{{ install_soa_rsp_file }}"

  - name: "Using a template to create the inventory"
    template:
      src: oraInst.loc.j2
      dest: "{{ oracle_inventory_file }}"

  # In OFM 12.2.1.4 Weblogic and SOA can be installed in just one step
  # In the past it was Weblogic first and then SOA on top of Weblogic
  - name: "Installing Weblogic and SOA"
    command: "{{ install_java_home }}/bin/java \
      -{{ install_soa_memory }} -jar {{ staging_directory }}/{{ install_soa_staging }}/{{ install_soa_file }} -silent \
      -responseFile {{ install_soa_rsp_file }} \
      -invPtrLoc {{ oracle_inventory_file }}"
