---
# tasks file for directories

 # To create some of the main directories used to install 
 # Oracle Weblogic and SOA
 - name: Creating main directories
   file:
     path: "{{ item }}"
     state: directory
     owner: "{{ oracle_user }}"
     group: "{{ oracle_group }}"
     mode: 0755
   loop:
     - "{{ staging_directory }}"
     - "{{ oracle_home }}"
     - "{{ patch_directory }}"

 # To create directories inside staging directories
 - name: "Creating directories inside {{ staging_directory }}"
   file:
     path: "{{ staging_directory }}/{{ item.staging }}"
     state: directory
     owner: "{{ oracle_user }}"
     group: "{{ oracle_group }}"
     mode: 0755
   with_items:
     - "{{ soa_installers }}"

 # To copy installers into staging directory
 - name: "Copying installers into {{ staging_directory }}"
   copy:
     src: "{{ source_directory }}/{{ item.filename }}"
     dest: "{{ staging_directory }}/{{ item.staging }}"
     owner: "{{ oracle_user }}"
     group: "{{ oracle_group }}"
     mode: '0755'
   with_items:
     - "{{ soa_installers }}"